language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - chmod +x tests/bin/install-apcu.sh
  - ./tests/bin/install-apcu.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --prefer-source --dev install
  - cp phpunit.xml.dist phpunit.xml

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./

after_script:
  - php vendor/bin/coveralls -v
